### ISSUE TITLE
Enabling sync replication on barman doesn't work until the receiver is restarted

### ISSUE THREAD

**Issue by xstasi** [EnterpriseDB/barman#130] opened 2017-10-19 10:40 UTC
If you add barman as one of the potential synchronous standbys, the wal receiver does not detect the change until it's restarted.

This means that if barman is your only available standby and the receiver has not been restarted yet, the master will show barman as sync but hang on commits nonetheless.

This should be fixed if possible, or otherwise at least documented.

**Comment by slavniyteo** [comment] 2019-01-23 13:41
The problem is [there](https://github.com/2ndquadrant-it/barman/blob/ccfbc1fa3992eeefac944dd1e5746695fc16ade6/barman/wal_archiver.py#L921). If you configure postgres with `synchronous_standby_names = *`, `syncnames` contains `[ * ]` and check on line 921 fales.

When you explicitly write barman's name into `synchronous_standby_names`, everything works fine.

P.S. Tested with Postgresql 9.6

**Comment by amenonsen** [comment] 2021-03-03 12:49
As part of an effort to pick up maintenance of Barman, I'm closing this and many other old open issues in this repository.

**Closed by amenonsen** 2021-03-03 12:49 UTC
Labels: enhancement
