### ISSUE TITLE
Timezones of "Begin time" and "End time" are inconsistent

### ISSUE THREAD

**Issue by rkrzr** [EnterpriseDB/barman#206] opened 2019-04-02 15:05 UTC
## The Problem

I ran into a small display issue, where the reported timezone of the timestamp of the "Begin time" is different than the timezone of the timestamp of the "End time" of a backup:

```
    Begin time           : 2019-04-01 21:21:05+02:00
    End time             : 2019-04-01 20:06:36.513013+00:00
```

I don't believe this has any serious consequences, but it would be nice to display this consistently.

## Expected behavior

I would expect both timestamps to use the same timezone.
It could be either the timezone of the server, or both could be normalized to UTC (probably best).

**Comment by tuanbo91** [comment] 2019-05-06 08:27
Same for me:
```
    Begin time           : 2019-05-06 03:55:37+07:00
    End time             : 2019-05-06 03:55:52.463454-04:00
```

**Comment by mikewallace1979** [comment] 2021-09-07 21:39
The root of this issue turned out to be quite surprising (well, to me anyway).

I could not reproduce it at first - from Barman 2.13 all the way back to Barman 2.7 (the latest release before this issue was filed) I was seeing `Begin time` and `End time` in the UTC timezone, regardless of the timezone set on the barman server, e.g.:

```
    Begin time           : 2021-09-07 12:45:16.989370+00:00
    End time             : 2021-09-07 12:45:17.712935+00:00
```

Taking a look at the code to understand why this might be shows that we just [read the timestamps from the backup info](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/output.py#L736-L737) - there is no difference in how they are read from `backup.info`, both [begin_time](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/infofile.py#L438) and [end_time](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/infofile.py#L444) are loaded via the same [load_datetime_tz](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/infofile.py#L82-L98) function.

So the issue must instead be related to how we determine the `begin_time` and `end_time` values for the `backup.info` file. This happens in `backup_executor.BackupStrategy` and its subclasses. For the common use case of concurrent backup, we [set the backup info using the response of postgres.start_concurrent_backup](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/backup_executor.py#L1810-L1812). What actually happens here is that `postgres.start_concurrent_backup` runs [the following SQL](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/postgres.py#L1140-L1145):

```
                "SELECT location, "
                "(SELECT timeline_id "
                "FROM pg_control_checkpoint()) AS timeline, "
                "now() AS timestamp "
                "FROM pg_start_backup(%s, %s, FALSE) AS location",
                (label, self.immediate_checkpoint),
```

The value of "timestamp" is then [assigned to backup_info.begin_time](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/backup_executor.py#L1424). `end_time` is set in backup_info in [almost the exact same way](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/postgres.py#L1221-L1229).

So this tells us why the timezone of the barman server wasn't making a difference - `begin_time` and `end_time` are determined by the timezone of the PostgreSQL server. I set `timezone = 'Pacific/Easter'` in `postgres.conf` and took a new backup and confirmed the timezone for `Begin time` and `End time` had changed:

```
    Begin time           : 2021-09-07 10:36:27.077259-05:00
    End time             : 2021-09-07 10:36:37.212193-05:00
```

So, no closer to *actually* reproducing the issue but at least we know where the `begin_time` and `end_time` values come from.

Taking another look at the code in `backup_executor.py`, there is another function which can set the `begin_time` value in `backup.info` - [_backup_info_from_backup_label](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/backup_executor.py#L1513). This function is called during [PostgresBackupStrategy.stop_backup](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/backup_executor.py#L1572) as well as during [ConcurrentBackupStrategy._pgespresso_start_backup](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/backup_executor.py#L1782). pgespresso relates to older (<9.6) versions of PostgreSQL so let's focus on the call in `PostgresBackupStrategy.stop_backup`.

`PostgresBackupStrategy` is used when barman is configured to do streaming backups via pg_basebackup - this explains why I couldn't reproduce the issue earlier: my barman environment was configured to use Rsync. Changing to pg_basebackup by setting `backup_method = postgres` in the barman config and taking a new backup yielded the following on `barman show backup`:

```
    Begin time           : 2021-09-07 16:30:45+00:00
    End time             : 2021-09-07 11:31:24.826397-05:00
```

Now we have reproduced the issue it's fairly easy to understand from the code what is going on:
1. When the pg_basebackup is started, `begin_time` is set using the response from [postgres.current_xlog_info](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/backup_executor.py#L1556) which selects [CURRENT_TIMESTAMP](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/postgres.py#L621) as `timestamp`.
2. When the pg_basebackup is stopped, [_backup_info_from_backup_label](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/backup_executor.py#L1572) is called on `backup_info` causing `begin_wal` (currently the timestamp from the PostgreSQL server, consistent with the way other backups work) to be replaced with the value of [START TIME:](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/backup_executor.py#L1498) in the backup_label. This appears to always be a UTC timestamp regardless of the PostgreSQL timezone.
3. Finally [_backup_info_from_stop_location](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/backup_executor.py#L1581) is called, passing a new `CURRENT_TIMESTAMP` from a new call to `postgres.current_xlog_info` which sets `end_time` to the timestamp from the PostgreSQL server.

Thus, `begin_time` is a UTC timestamp and `end_time` has the same timezone as the PostgreSQL server.

A simple fix here would be to just patch [_backup_info_from_backup_label](https://github.com/EnterpriseDB/barman/blob/2ff4fc934d592356edc9f1848601158717389515/barman/backup_executor.py#L1486-L1514) so that it only populates `begin_time` if it is not already set. This would allow that function to work as it currently does for pgespresso backups and avoid clobbering the timestamp from the PostgreSQL server when running a pg_basebackup. Timezones for `begin_time` and `end_time` for `backup_method = postgres` backups would then be consistent with each other and consistent with those for Rsync backups.

**Comment by mikewallace1979** [comment] 2021-09-24 11:50
Taking another look at this I think we can remove the call to `_backup_info_from_backup_label` altogether because all of the information it retrieves is already present in the `backup_info`, having been read directly from PostgreSQL via [_backup_info_from_start_location](https://github.com/EnterpriseDB/barman/blob/33ce3d35fe72458ba8e36fae1e8b492109743a17/barman/backup_executor.py#L1556).

The specific fields are:

- begin_time
- begin_xlog
- timeline
- begin_wal
- begin_offset

Inspecting the contents of [_backup_info_from_start_location](https://github.com/EnterpriseDB/barman/blob/33ce3d35fe72458ba8e36fae1e8b492109743a17/barman/backup_executor.py#L1413-L1451) and [_backup_info_from_backup_label](https://github.com/EnterpriseDB/barman/blob/33ce3d35fe72458ba8e36fae1e8b492109743a17/barman/backup_executor.py#L1486-L1514) shows both functions do indeed populate the same fields in `backup_info`.

Looking at the commit history tells us the following:

1. When `PostgresBackupStrategy` was added in 1dd8ea8c the behaviour was to [populate backup_info from the the backup label](https://github.com/EnterpriseDB/barman/commit/1dd8ea8c#diff-e0e31b05d98a2066bbda158c9649402161eead59ed0b443b7b5acbbc006e799aR1050) and the logic which retrieved it directly from PostgreSQL was not present.
2. `PostgresBackupStrategy` was updated in b9233e42 to [retrieve these backup_info fields directly from PostgresSQL](https://github.com/EnterpriseDB/barman/commit/b9233e42#diff-e0e31b05d98a2066bbda158c9649402161eead59ed0b443b7b5acbbc006e799aR1121) however the call to populate backup_info from the backup label was not removed, resulting in the behaviour we still get today where backup label values replace the values already there (causing the timezone to change for begin_wal). `ConcurrentBackupStrategy` did the same thing as it also had a call to `_backup_info_from_backup_label`.
3. In 8be0c152 `ConcurrentBackupStrategy` was updated to [remove the call to _backup_info_from_backup_label](https://github.com/EnterpriseDB/barman/commit/8be0c15256ab43f89875c903162b9640b7182713#diff-e0e31b05d98a2066bbda158c9649402161eead59ed0b443b7b5acbbc006e799aL1403) but `PostgresBackupStragey` was not.

So unless there was a good reason for continuing to populate backup_info from the backup label when using the `PostgresBackupStrategy`, it seems reasonable to just remove that call altogether.

**Comment by mikewallace1979** [comment] 2021-09-24 14:21
It turns out `PostgresBackupStragey` still relies on reading the backup label when backing up a server which is in recovery mode. We therefore cannot simply remove the call to `_backup_info_from_backup_label` and instead we need to take the original approach of not overwriting begin_time.

**Closed** 2021-10-29 20:03 UTC
