### ISSUE TITLE
Geo redundancy with custom path configuration file fails on list-backup

### ISSUE THREAD

**Issue by martinmarques** [EnterpriseDB/barman#371] opened 2021-07-28 11:45 UTC
Per ticket RT71438 it was reported an issue with barman's passive server setup when using custom path configuration files with the `-c` barman option.

The problem only seems to manifest when listing the backups of the passive server, not for syncing the backups or the WAL files. In this case, the `list-backup` command will return an "ERROR: unknown server <server-name>"

This seems related to the fact that the server in question is not defined in the default path of the configuration which is used on the passive server-side so there is a mismatch of expected servers.

**Comment by mikewallace1979** [comment] 2021-09-06 11:45
I have spent some time looking at this one and have a proposed patch (to follow shortly).

## Reproduction

Based on the information in RT71438 I have reproduced the issue as explained below.

### Environment

Both the primary and passive Barman nodes have configuration files located in the same non-standard location on their local filesystem and barman is  invoked with `barman -c ${PATH_TO_CONFIG}` on both the primary and passive nodes.

The system configuration for barman is available at `/etc/barman.conf` however it is not used, has not been customized and does not reference any of the servers being backed up.

### Steps to reproduce

In a new environment with the above configuration, take a backup on the primary node so that there is something which should be synced, e.g. for a server named `geo-primary` with config at `/var/lib/barman/custom_config.conf`:

    $ barman -c /var/lib/barman/custom_config.conf backup geo-primary

Run `barman check` to verify everything is healthy:

```
$ barman -c /var/lib/barman/custom_config.conf check geo-primary
Server geo-primary:
	PostgreSQL: OK
	...
	archiver errors: OK
```

Now run `barman cron` on the passive node - amongst other things this should generate the sync-info for the server and store it in a local file named `primary.info`:

    $ barman -c /var/lib/barman/custom_config.conf cron
    ERROR: Failed to retrieve the primary node status: sync-info execution on remote primary server geo-primary failed: ERROR: Unknown server 'geo-primary'

We can also try running `sync-info` against the primary node which will fail in the same way:

    $ barman -c /var/lib/barman/custom_config.conf sync-info geo-primary --primary
    ERROR: sync-info execution on remote primary server geo-primary failed: ERROR: Unknown server 'geo-primary'

Running `sync-wals` will fail due to the absence of the `primary.info` file:

    $ barman -c /var/lib/barman/custom_config.conf sync-wals geo-primary
    ERROR: WAL synchronisation for server geo-primary failed with: Cannot open primary.info file for server geo-primary: [Errno 2] No such file or directory: '/var/lib/barman/geo-primary/primary.info'

Attempting to sync a specific backup also fails due to the missing `primary.info` file:

    $ barman -c /var/lib/barman/custom_config.conf sync-backup geo-primary 20210906T104518
    ERROR: Cannot open primary.info file for server geo-primary: [Errno 2] No such file or directory: '/var/lib/barman/geo-primary/primary.info'

### Expected results

The initial `barman cron` above should succeed with an output like this:

    $ barman --log-level=DEBUG -c /var/lib/barman/custom_config.conf cron
    Starting copy of backup 20210903T150705 for server geo-primary
    Started copy of WAL files for server geo-primary

The `sync-info --primary` command should also complete successfully.

`barman cron` should also write a `primary.info` file which would enable the `sync-wals` and `sync-backup` commands to complete successfully (they do not need to interact with barman on the primary node, they rely on the data in `primary.info` instead).

## Analysis

This reproduction confirms the issue identified here and in RT71438, specifically the reason why `barman -c ${PATH_TO_CONFIG} cron` and `barman -c ${PATH_TO_CONFIG} sync-info ${SERVER_NAME} --primary` fail is that the `-c` option is not used when `barman cron` [invokes barman on the primary node](https://github.com/EnterpriseDB/barman/blob/8656d01bc82bfafff7f417ff7e3aa43c82b33a04/barman/server.py#L3274) for the purposes of generating the `sync-info` data.

The specific chain of events is:

1. `barman -c ${PATH_TO_CONFIG} cron` is run on the passive node and it invokes `barman sync-info` on the primary node.
1. The `barman sync-info` command on the primary node uses the default config located at `/etc/barman.conf`.
2. This default config has no reference to the named server (in this case `geo-primary`).
3. The `barman sync-info` on the primary node fails with `Unknown server`.
4. The parent command on the passive node therefore errors out and does not write any sync info to `primary.info`.
5. Subsequent `sync-backup` and `sync-wals` commands, which depend on this `primary.info` file, always fail due to the missing `primary.info` file.

## Proposed fix

The simplest fix for this is to include the local `-c ${PATH_TO_CONFIG} option in the remote `barman sync-info` command. This would fix both `barman cron` and `barman sync-info ${SERVER_NAME} --primary`, which would have the knock-on effect of also fixing `sync-backup` and `sync-wals` (as the `primary.info` would be created successfully by the cron command).

It would, however, break any geo-redundancy environments where the passive barman server uses a custom config file but the primary barman server uses a config file in one of the default locations. While we do not know anyone is relying on this behavior we cannot assume that is the case.

What I propose is that we add a new server-level config variable which determines whether the `-c` option should be forwarded - something like a boolean named `forward_config_path`. It should default to false however anyone requiring the remote barman command on the primary node to use the same `-c` option can set it to true.

In a future major version release we could consider making the default true and adding it to the list of breaking changes.

Note: an alternative fix would be to add a `remote_config_path` (or similar) config variable where users can specify the exact path of the config file on the primary barman server. We could even go one step further and have a `primary_barman_command` option which allows users to specify the exact barman invocation that should be used. However this approach creates additional flexibility which is not being asked for and could result in more complexity in geo-redundancy environments. So on that basis I think simply forwarding the config path (subject to a `forward_config_path` option) is the appropriate fix here.

**Closed** 2021-09-07 13:13 UTC
