### ISSUE TITLE
When barman is updated on a RPM based system, it overwrites an existing /etc/barman.conf config file.

### ISSUE THREAD

**Issue by mbalmer** [EnterpriseDB/barman#553] opened 2022-04-11 08:59 UTC
This problem applies to Red Hat (RPM) based installs only.

When the barman package is updated, it will overwrite an existing /etc/barman.conf if was modified config file with the version in the rpm package.  It will, however, save the old /etc/barman.conf in /etc/barman.conf.rpmsave.  But the damage is already done, e.g. if the barman.conf specified a different location for the backups.

So instead of marking the config file in the spec files as

%config /etc/barman.conf

it should really be marked as

%config(noreplace) /etc/barman.conf

This way the version from the rpm package will be installed as /etc/barman.conf.rpmnew and /etc/barman.conf will remain untouched.

(FWIW:  The current behaviour has caused us repeatedly troubles, we keep backup on a separate disk, and once /etc/barman.conf was overwritte all backup went to /var/lib/barman, slowly filling the main system disk...)

**Comment by mikewallace1979** [comment] 2022-04-26 10:17
@mbalmer Thanks for reporting this - can you please share the following:

* The OS distribution and version you are using.
* The barman versions you have been upgrading to/from.
* The repo from which you obtained the barman rpms.

So far I've been unable to reproduce the issue so I'm hoping the above questions will help me understand what I'm missing.

The rpms which are published at the [EDB](https://yum.enterprisedb.com) and [2ndQ](https://dl.2ndquadrant.com) repositories are built from a spec file which already uses `%config(noreplace)` for `/etc/barman.conf`. I've tested upgrading from barman 2.15 to 2.16 (the most recent time the config file in the package changed) on CentOS 7 and Rocky 8 and verified that an edited `/etc/barman.conf` file is untouched and a new `/etc/barman.conf.rpmnew` file is created as expected. I've also queried the barman 2.19 rpm files from the EDB, 2ndQ and PGDG repositories and verified the correct flag for noreplace is set for `/etc/barman.conf`.

So it looks like I'm missing something but I'm not sure exactly what - if you can share the information requested above and any other additional context you think may be helpful then I can take another look and hopefully get to the bottom of it.

**Comment by martinmarques** [comment] 2024-11-22 10:33
@mbalmer If you are using packages from PGDG, you should open a ticket in the PGDG rpm redmine project. Closing this now as it's been opened for some time

**Closed by martinmarques** 2024-11-22 10:33 UTC
Labels: triage
