### ISSUE TITLE
Wals retention issue

### ISSUE THREAD

**Issue by mcondamin** [EnterpriseDB/barman#712] opened 2022-12-05 16:17 UTC
Hi,

I have a problem regarding the retention of wals on my database server which is not backed up every day.

Let me explain :
I have 2 database servers in master/slave. I made full backups with barman every night **only on the slave server** with a 7 day retention window. So far no problem the wals and the base backups are well kept for 7 days.

I also configured Barman to receive wals from the master in case I had to switch and perform backups on it, for example if the slave server was under maintenance or unavailable. So Barman does receive the wals, but it doesn't perform any purging, which causes the wals to clump together on the server and saturate the disk space. 

Is this normal behavior and I have to purge manually or am I missing something?

Below are the configurations:
```
[db01]
description = "Server db01 Master - Streaming"
ssh_command = ssh postgres@db01.ha.payxpert.com
conninfo = user=barman host=db01.ha.payxpert.com dbname=postgres port=5432
archiver = false
active = true
backup_method = postgres
backup_compression = gzip
backup_options = concurrent_backup
compression = gzip
minimum_redundancy = 0
path_prefix = /usr/lib/postgresql/13/bin/
retention_policy = RECOVERY WINDOW OF 7 DAYS
retention_policy_mode = auto
slot_name = barman
streaming_archiver = true
streaming_conninfo = user=streaming_barman host=db01.ha.payxpert.com
wal_retention_policy = main
```
```
[db02]
description = "Server db02 Slave - Streaming"
ssh_command = ssh postgres@db02.ha.payxpert.com
conninfo = user=barman host=db02.ha.payxpert.com dbname=postgres port=5432
archiver = false
active = true
backup_method = postgres
backup_compression = gzip
backup_options = concurrent_backup
compression = gzip
minimum_redundancy = 0
path_prefix = /usr/lib/postgresql/13/bin/
primary_conninfo = user=barman host=db01.ha.payxpert.com dbname=postgres port=5432
retention_policy = RECOVERY WINDOW OF 7 DAYS
retention_policy_mode = auto
slot_name = barman
streaming_archiver = true
streaming_conninfo = user=streaming_barman host=db02.ha.payxpert.com
wal_retention_policy = main
```

```
mco@pg-barman:~$ sudo -u barman barman check db01 
Server db01:
	PostgreSQL: OK
	superuser or standard user with backup privileges: OK
	PostgreSQL streaming: OK
	wal_level: OK
	replication slot: OK
	directories: OK
	retention policy settings: OK
	backup maximum age: OK (no last_backup_maximum_age provided)
	backup minimum size: OK (0 B)
	wal maximum age: OK (no last_wal_maximum_age provided)
	wal size: OK (0 B)
	compression settings: OK
	failed backups: OK (there are 0 failed backups)
	minimum redundancy requirements: OK (have 0 backups, expected at least 0)
	pg_basebackup: OK
	pg_basebackup compatible: OK
	pg_basebackup supports tablespaces mapping: OK
	systemid coherence: OK (no system Id stored on disk)
	pg_receivexlog: OK
	pg_receivexlog compatible: OK
	receive-wal running: OK
	archiver errors: OK
```

And the problem for db01 : 
```
mco@pg-barman:~$ sudo ls -l /var/lib/barman/db01/wals
total 1040
-rw------- 1 barman barman     96 Nov 16 16:03 00000005.history
drwxr-xr-x 2 barman barman  12288 Nov 17 09:01 00000005000008F5
drwxr-xr-x 2 barman barman  16384 Nov 17 20:22 00000005000008F6
drwxr-xr-x 2 barman barman  16384 Nov 18 13:47 00000005000008F7
drwxr-xr-x 2 barman barman  16384 Nov 19 11:57 00000005000008F8
drwxr-xr-x 2 barman barman  16384 Nov 19 22:14 00000005000008F9
drwxr-xr-x 2 barman barman  16384 Nov 20 20:23 00000005000008FA
drwxr-xr-x 2 barman barman  16384 Nov 21 14:33 00000005000008FB
drwxr-xr-x 2 barman barman  16384 Nov 21 14:42 00000005000008FC
drwxr-xr-x 2 barman barman  20480 Nov 22 09:07 00000005000008FD
drwxr-xr-x 2 barman barman  16384 Nov 22 21:49 00000005000008FE
drwxr-xr-x 2 barman barman  16384 Nov 23 15:23 00000005000008FF
drwxr-xr-x 2 barman barman  20480 Nov 24 08:53 0000000500000900
drwxr-xr-x 2 barman barman  20480 Nov 24 15:38 0000000500000901
drwxr-xr-x 2 barman barman  16384 Nov 25 09:23 0000000500000902
drwxr-xr-x 2 barman barman  20480 Nov 25 21:01 0000000500000903
drwxr-xr-x 2 barman barman  16384 Nov 26 17:09 0000000500000904
drwxr-xr-x 2 barman barman  16384 Nov 27 01:16 0000000500000905
drwxr-xr-x 2 barman barman  16384 Nov 27 16:41 0000000500000906
drwxr-xr-x 2 barman barman  16384 Nov 28 08:58 0000000500000907
drwxr-xr-x 2 barman barman  16384 Nov 28 19:31 0000000500000908
drwxr-xr-x 2 barman barman  16384 Nov 29 11:53 0000000500000909
drwxr-xr-x 2 barman barman  20480 Nov 29 19:50 000000050000090A
drwxr-xr-x 2 barman barman  16384 Nov 30 12:07 000000050000090B
drwxr-xr-x 2 barman barman  20480 Nov 30 19:53 000000050000090C
drwxr-xr-x 2 barman barman  16384 Dec  1 12:39 000000050000090D
drwxr-xr-x 2 barman barman  20480 Dec  1 18:27 000000050000090E
drwxr-xr-x 2 barman barman  16384 Dec  1 18:36 000000050000090F
drwxr-xr-x 2 barman barman  16384 Dec  2 11:16 0000000500000910
drwxr-xr-x 2 barman barman  20480 Dec  2 19:54 0000000500000911
drwxr-xr-x 2 barman barman  16384 Dec  3 16:07 0000000500000912
drwxr-xr-x 2 barman barman  16384 Dec  4 11:13 0000000500000913
drwxr-xr-x 2 barman barman  16384 Dec  4 22:54 0000000500000914
drwxr-xr-x 2 barman barman  16384 Dec  5 15:03 0000000500000915
drwxr-xr-x 2 barman barman   4096 Dec  5 16:09 0000000500000916
-rw-r--r-- 1 barman barman 475532 Dec  5 16:09 xlog.db
```

Ok for db02 :
```
mco@pg-barman:~$ sudo ls -l /var/lib/barman/db02/wals
total 472
-rw------- 1 barman barman     96 Nov 16 10:32 00000005.history
drwxr-xr-x 2 barman barman  16384 Dec  5 07:28 0000000500000907
drwxr-xr-x 2 barman barman  16384 Nov 28 19:31 0000000500000908
drwxr-xr-x 2 barman barman  16384 Nov 29 11:53 0000000500000909
drwxr-xr-x 2 barman barman  20480 Nov 29 19:50 000000050000090A
drwxr-xr-x 2 barman barman  16384 Nov 30 12:07 000000050000090B
drwxr-xr-x 2 barman barman  20480 Nov 30 19:53 000000050000090C
drwxr-xr-x 2 barman barman  16384 Dec  1 12:39 000000050000090D
drwxr-xr-x 2 barman barman  20480 Dec  1 18:27 000000050000090E
drwxr-xr-x 2 barman barman  16384 Dec  1 18:36 000000050000090F
drwxr-xr-x 2 barman barman  16384 Dec  2 11:16 0000000500000910
drwxr-xr-x 2 barman barman  20480 Dec  2 19:54 0000000500000911
drwxr-xr-x 2 barman barman  16384 Dec  3 16:07 0000000500000912
drwxr-xr-x 2 barman barman  16384 Dec  4 11:13 0000000500000913
drwxr-xr-x 2 barman barman  16384 Dec  4 22:54 0000000500000914
drwxr-xr-x 2 barman barman  16384 Dec  5 15:03 0000000500000915
drwxr-xr-x 2 barman barman   4096 Dec  5 16:09 0000000500000916
-rw-r--r-- 1 barman barman 206821 Dec  5 16:09 xlog.db
```

Thank you for your help !

**Comment by mikewallace1979** [comment] 2022-12-05 22:34
This is expected behaviour, for now. The deletion of WAL files only happens when backups are deleted so if no backups are ever taken then the WALs will accumulate indefinitely.

This is because the existing WAL deletion logic uses the presence of backups to determine whether a WAL is required. If no backups exist which either require a given WAL for backup consistency *or* would require that WAL for point-in-time recovery, then that WAL will be deleted.

Using Barman as a WAL-only store isn't currently a supported feature and you may find other surprising behaviours with the configuration - for instance when you take the first backup for a server Barman will delete any WALs which accumulated before the begin_wal of the backup (since they will not be needed to recover any backup). In scenarios like this, that might not be the behaviour you want.

Taking a step up a level, there is work planned for 2023 where we will add cluster-awareness to Barman, so that instead of configuring a primary and a standby as separate servers in Barman, you would be able to add multiple hosts and tell Barman whether you want to take backups from the primary or from a standby. Barman would then figure out the rest and users would not need to worry about maintaining WAL archives for multiple server configurations.

I think that such a feature would address the underlying problem here by removing the need to configure two separate servers in Barman - what do you think?

**Comment by martinmarques** [comment] 2022-12-06 11:35
To add to Mike's comment, until barman is cluster-aware the way to configure this is by adding steps to your failover process to reconfigure the backup system.

In such a case, you could have the old primary configured in barman, but not active (no archiving, no backups). On failover you would need to perform the following steps on the barman server, in the other below, but after you have the cluster with a primary and a standby (the old primary rejoined as a new standby):

1) Activate the standby server in barman
2) Make sure that there are WALs being archived. Run `pg_switch_wal()` a couple of times
3) Run a backup on the newly activated standby
4) Deactivate the new primary (formally a standby where you were taking backups from)

An alternative option that we used a lot in the old infrastructure in 2ndQuadrant was to continuously backup primary and standby. This is much easier to maintain and set up but requires double space usage. So it's convenient for small database clusters.

**Comment by mcondamin** [comment] 2022-12-15 13:53
Hello, sorry for the late reply and thank you both for answering me, it's much clearer now.

Regarding the backup of the postgres master node, I don't want to make it a WAL-only store (the logs are already saved on the other node), but just that barman be ready to backup this node with the command 'barman backup db01'.
To summarize I don't care about the backup of wals on this node, I just want it to be ready-to-backup.

I appreciate the fact that barman is constantly evolving and I can't wait for this new "cluster" feature in barman to be implemented in the tool! This is exactly the feature I'm missing, which would allow ease of administration as well as saving space on the server!
Can't wait to hear about its development!

In the meantime I think I will continue to keep the node ready to be backed up and purge the wals daily (which would be deleted on the first backup anyway).
The idea of backing up both the primary and the standby was a good idea, unfortunately the cluster is several hundred GB so it would take up too much space.

Thank you again for your feedback, have a good holiday!

**Comment by martinmarques** [comment] 2024-08-02 09:54
BTW, I'm closing this now, given that we added barman models which can be used to create cluster aware backups with barman. You will need 3.10 or newer for this

**Closed by martinmarques** 2024-08-02 09:54 UTC
Labels: cluster-awareness
