### ISSUE TITLE
A lot of "Forcing StreamingConnection cleanup during process shut down." warning messages in log file.

### ISSUE THREAD

**Issue by kraynopp** [EnterpriseDB/barman#652] opened 2022-08-30 12:47 UTC
I see following in my log file:

> 2022-08-30 15:21:02,173 [6124] barman.postgres WARNING: Forcing StreamingConnection cleanup during process shut down.
> 2022-08-30 15:21:02,350 [6127] barman.wal_archiver INFO: No xlog segments found from streaming for barman-db.

I suppose that this warning should not be here and something is wrong.

Log file with debug:
> 2022-08-30 15:26:01,542 [6183] barman.config DEBUG: Including configuration file: barman-db.conf
> 2022-08-30 15:26:01,542 [6183] barman.cli DEBUG: Initialised Barman version 3.0.1 (config: /etc/barman/barman.conf, args: {'color': 'auto', 'quiet': True, 'debug': False, 'format': 'console', 'command': 'cron', 'keep_descriptors': False, 'func': <function cron at 0x7fa126c31820>})
> 2022-08-30 15:26:01,553 [6183] barman.backup_executor DEBUG: The default backup strategy for postgres backup_method is: concurrent_backup
> 2022-08-30 15:26:01,553 [6183] barman.command_wrappers DEBUG: Command: ['/usr/bin/pg_basebackup', '--version']
> 2022-08-30 15:26:01,560 [6183] barman.command_wrappers DEBUG: Command return code: 0
> 2022-08-30 15:26:01,560 [6183] barman.command_wrappers DEBUG: Command stdout: pg_basebackup (PostgreSQL) 14.4
> 
> 2022-08-30 15:26:01,560 [6183] barman.command_wrappers DEBUG: Command stderr: 
> 2022-08-30 15:26:01,565 [6183] barman.server DEBUG: Retention policy for server barman-db: RECOVERY WINDOW OF 1 DAYS
> 2022-08-30 15:26:01,565 [6183] barman.server DEBUG: WAL retention policy for server barman-db: MAIN
> 2022-08-30 15:26:01,565 [6183] barman.command_wrappers DEBUG: BarmanSubProcess: ['/usr/bin/python3', '/usr/bin/barman', '-c', '/etc/barman/barman.conf', '-q', 'archive-wal', 'barman-db']
> 2022-08-30 15:26:01,578 [6183] barman.command_wrappers DEBUG: BarmanSubProcess: subprocess started. pid: 6186
> 2022-08-30 15:26:01,579 [6183] barman.server DEBUG: Another STREAMING ARCHIVER process is running for server barman-db
> 2022-08-30 15:26:01,580 [6183] barman.retention_policies DEBUG: Reporting backup 20220830T151809 for server barman-db as VALID (newer than 2022-08-29 15:26:01.580351+03:00)
> 2022-08-30 15:26:01,580 [6183] barman.postgres WARNING: Forcing StreamingConnection cleanup during process shut down.
> 2022-08-30 15:26:01,736 [6186] barman.config DEBUG: Including configuration file: barman-db.conf
> 2022-08-30 15:26:01,737 [6186] barman.cli DEBUG: Initialised Barman version 3.0.1 (config: /etc/barman/barman.conf, args: {'color': 'auto', 'quiet': True, 'debug': False, 'format': 'console', 'command': 'archive-wal', 'config': '/etc/barman/barman.conf', 'server_name': 'barman-db', 'func': <function archive_wal at 0x7efe892fae50>})
> 2022-08-30 15:26:01,747 [6186] barman.backup_executor DEBUG: The default backup strategy for postgres backup_method is: concurrent_backup
> 2022-08-30 15:26:01,748 [6186] barman.command_wrappers DEBUG: Command: ['/usr/bin/pg_basebackup', '--version']
> 2022-08-30 15:26:01,754 [6186] barman.command_wrappers DEBUG: Command return code: 0
> 2022-08-30 15:26:01,754 [6186] barman.command_wrappers DEBUG: Command stdout: pg_basebackup (PostgreSQL) 14.4
> 
> 2022-08-30 15:26:01,754 [6186] barman.command_wrappers DEBUG: Command stderr: 
> 2022-08-30 15:26:01,759 [6186] barman.server DEBUG: Retention policy for server barman-db: RECOVERY WINDOW OF 1 DAYS
> 2022-08-30 15:26:01,759 [6186] barman.server DEBUG: WAL retention policy for server barman-db: MAIN
> 2022-08-30 15:26:01,759 [6186] barman.server DEBUG: Starting archive-wal for server barman-db
> 2022-08-30 15:26:01,760 [6186] barman.wal_archiver INFO: No xlog segments found from streaming for barman-db.

**Comment by mikewallace1979** [comment] 2022-08-30 16:42
@kraynopp Thanks for reporting this - I agree this warning suggests something is wrong.

I wasn't able to reproduce it at first but after adding `backup_method = postgres` and setting `bandwidth_limit` for the server in the barman config I now get similar behaviour:

```
2022-08-30 15:43:51,547 [1593] barman.cli DEBUG: Initialised Barman version 3.0.1 (config: /etc/barman.conf, args: {'color': 'auto', 'quiet': False, 'debug': False, 'format': 'console', 'command': 'cron', 'keep_descriptors': False, 'func': <function cron at 0x7f5690c9bc10>})
2022-08-30 15:43:51,557 [1593] barman.backup_executor DEBUG: The default backup strategy for postgres backup_method is: concurrent_backup
2022-08-30 15:43:51,558 [1593] barman.command_wrappers DEBUG: Command: ['/usr/bin/pg_basebackup', '--version']
2022-08-30 15:43:51,585 [1593] barman.command_wrappers DEBUG: Command return code: 0
2022-08-30 15:43:51,585 [1593] barman.command_wrappers DEBUG: Command stdout: pg_basebackup (PostgreSQL) 14.2 (Ubuntu 14.2-1.pgdg20.04+1)
2022-08-30 15:43:51,585 [1593] barman.command_wrappers DEBUG: Command stderr: 
2022-08-30 15:43:51,596 [1593] barman.server DEBUG: Retention policy for server main: RECOVERY WINDOW OF 1 DAYS
2022-08-30 15:43:51,596 [1593] barman.server DEBUG: WAL retention policy for server main: MAIN
2022-08-30 15:43:51,597 [1593] barman.command_wrappers DEBUG: BarmanSubProcess: ['/usr/bin/python3', '/usr/bin/barman', '-c', '/etc/barman.conf', '-q', 'archive-wal', 'main']
2022-08-30 15:43:51,600 [1593] barman.command_wrappers DEBUG: BarmanSubProcess: subprocess started. pid: 1595
2022-08-30 15:43:51,600 [1593] barman.server DEBUG: Another STREAMING ARCHIVER process is running for server main
2022-08-30 15:43:51,602 [1593] barman.retention_policies DEBUG: Reporting backup 20220830T152949 for server main as VALID (newer than 2022-08-29 15:43:51.602372+00:00)
2022-08-30 15:43:51,602 [1593] barman.retention_policies DEBUG: Reporting backup 20220830T150525 for server main as VALID (newer than 2022-08-29 15:43:51.602510+00:00)
2022-08-30 15:43:51,602 [1593] barman.postgres WARNING: Forcing StreamingConnection cleanup during process shut down.
```

The warnings come from the [atexit handler](https://github.com/EnterpriseDB/barman/blob/release/3.0.1/barman/postgres.py#L70-L81) which was added in https://github.com/EnterpriseDB/barman/commit/03dbbb7df17bef7915085597a80ea55d85472841 to warn about any connections which have not been closed when barman exits - so the fact that a connection is still open here is a bug.

It looks like we need to call [server.cron](https://github.com/EnterpriseDB/barman/blob/19abf787407170c774937457141875af6b6b3a77/barman/cli.py#L295) within a `closing` context manager in order to make sure the server connections are closed when they are no longer needed.

**Closed** 2022-09-02 10:40 UTC
Labels: bug
