### ISSUE TITLE
SSL error on primary_conninfo

### ISSUE THREAD

**Issue by pru-anixe** [EnterpriseDB/barman#685] opened 2022-10-30 21:13 UTC
Barman 3.2.0

I have backup configured to be executed on standby server

```
[sqlv2.dc.lan]
active = "True"
description = "Backup from standby"
ssh_command = ssh postgres@sqlv2.dc.lan
conninfo = "host=sqlv2.dc.lan user=barman dbname=postgres"
primary_conninfo = "host=sqlv1.dc.lan user=barman dbname=postgres"
backup_method = "rsync"
reuse_backup = "link"
backup_options = "concurrent_backup"
archiver = on
minimum_redundancy = "1"
retention_policy = "REDUNDANCY 7"`
```

sqlv2 config

```
archive_command = 'barman-wal-archive backup.dc.lan sqlv2.dc.lan %p'
archive_mode = always
wal_level = replica
hot_standby = on
```

starting the very first backup

```
barman backup sqlv2.dc.lan --reuse-backup=off
Starting backup using rsync-concurrent method for server sqlv2.dc.lan in /var/lib/barman/sqlv2.dc.lan/base/20221030T215301
Backup start at LSN: 32A/14006310 (000000010000032A00000014, 00006310)
Starting backup copy via rsync/SSH for 20221030T215301
WARNING: The usage of include directives is not supported for files that reside outside PGDATA.
Please manually backup the following files:
	/etc/postgresql/11/main/conf.d/25ansible_postgresql.conf

Copy done (time: 19 seconds)
Asking PostgreSQL server to finalize the backup.
```

and here it stops and waits endlessly

on standby, I can see

```
2022-10-30 21:55:20.879 CET [4764] barman@postgres WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (120 seconds elapsed)
2022-10-30 21:55:20.879 CET [4764] barman@postgres HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
```

I have tested connectivity via

```
barman-wal-archive --test backup.dc.lan sqlv2.dc.lan DUMMY
b'Ready to accept WAL files for the server sqlv2.dc.lan\n'
```

while on primary I see
```
2022-10-30 1:52:43.399 CET [2081] barman@postgres LOG:  SSL error: decryption failed or bad record mac
2022-10-30 1:52:43.399 CET [2081] barman@postgres LOG:  could not receive data from client: Connection reset by peer
```

barman check command says it's all green and its log doesn't show anything helpful (even with DEBUG level)

**Comment by mikewallace1979** [comment] 2022-10-31 12:17
Hi @pru-anixe - thanks for the detailed description of the issue.

I don't (yet) have a full explanation of what is going on but here's my current understanding:

1. The backup from the standby waiting for a WAL switch to occur on the primary. Once this occurs `archive_command` will be executed on the standby and the backup will complete.
2. Because your test `barman-wal-archive --test backup.dc.lan sqlv2.dc.lan DUMMY` on the standby is successful we know that when `archive_command` *does* run, the WAL archiving should work, however until the WAL switch on the primary happens, `archive_command` will not run on the standby.
3. Barman is supposed to use `primary_conninfo` to force the WAL switch on the primary in order to allow the backup to complete. Because `barman check` is passing, and `barman check` uses `primary_conninfo` to check the connection status, we know that the `primary_conninfo` connection is working.
4. During the backup the WAL switch on the primary does not happen successfully, therefore the stop backup command issued by Barman to the standby never completes.

Part of the problem is related to the two errors you see in the logs on the primary:

```
2022-10-30 1:52:43.399 CET [2081] barman@postgres LOG:  SSL error: decryption failed or bad record mac
2022-10-30 1:52:43.399 CET [2081] barman@postgres LOG:  could not receive data from client: Connection reset by peer
```

These happen because Barman is not creating a new connection to the primary after creating a new process to carry out the WAL switch - instead it reuses the connection from the parent process. This connection reuse in the forked process breaks the SSL connection resulting in these log messages.

However, this bug alone shouldn't be enough to stop the WAL switch from happening - when the connection fails it should be automatically recreated in the forked process which should allow the WAL switch on the primary to be performed successfully. I therefore wonder if there is a second issue which is preventing the WAL switch on the primary from occurring at all.

Could you please try running the following command on your Barman server to verify whether Barman is able to switch the WAL file on the primary outside of the stop backup context:

```
barman switch-wal sqlv2.dc.lan --force
```

This command performs the WAL switch on the primary via `primary_conninfo` but does not use a forked process so it is a good test of the WAL switch logic in isolation. If successful you should see output which looks something like this:

```
$ barman switch-wal standby --force
The WAL file 00000001000000000000007A has been closed on server 'standby'
```

The Barman logs should contain lines which look like this:

```
2022-10-31 12:01:44,387 [3007] barman.server INFO: Force a CHECKPOINT before pg_switch_wal()
2022-10-31 12:01:44,431 [3007] barman.server INFO: The WAL file 00000001000000000000007A has been closed on server 'standby'
```

and the PostgreSQL logs on the *primary* should contain something like these lines:

```
2022-10-31 13:01:44.412 CET [4191] LOG:  duration: 0.022 ms  statement: SELECT 1
2022-10-31 13:01:44.412 CET [4191] LOG:  duration: 0.040 ms  statement: SELECT pg_is_in_recovery()
2022-10-31 13:01:44.412 CET [4191] LOG:  duration: 0.022 ms  statement: SELECT 1
2022-10-31 13:01:44.412 CET [4191] LOG:  duration: 0.064 ms  statement: SELECT pg_walfile_name(pg_current_wal_insert_lsn())
2022-10-31 13:01:44.412 CET [4191] LOG:  duration: 0.023 ms  statement: SELECT 1
2022-10-31 13:01:44.418 CET [4191] LOG:  duration: 4.978 ms  statement: SELECT pg_walfile_name(pg_switch_wal())
2022-10-31 13:01:44.418 CET [4191] LOG:  duration: 0.050 ms  statement: SELECT 1
2022-10-31 13:01:44.418 CET [4191] LOG:  duration: 0.033 ms  statement: SELECT pg_walfile_name(pg_current_wal_insert_lsn())
```

If this is successful then it's likely the only issue during the stop backup is the connection reuse bug - if it is unsuccessful then the output or logs should provide further clues as to what else might be wrong.

Regardless of the output I'll file a new issue for the connection reuse bug.

**Comment by pru-anixe** [comment] 2022-10-31 12:27
Hello, thanks for the reply, so here's how it looks
command
```
barman switch-wal sqlv2.dc.lan --force
The WAL file 000000010000032A0000008F has been closed on server 'sqlv2.dc.lan'
```

barman log
```
2022-10-31 13:21:59,686 [102425] barman.server INFO: Force a CHECKPOINT before pg_switch_wal()
2022-10-31 13:21:59,881 [102425] barman.server INFO: The WAL file 000000010000032A0000008F has been closed on server 'sqlv2.dc.lan'
```

I don't see anything on psql log at v1 nor v2 but this may be related to some log lovel that's there

**Comment by mikewallace1979** [comment] 2022-10-31 13:36
Thanks for the additional info - since `barman switch-wal` is working fine I suspect the only bug involved is the [reuse of the PostgreSQL connection in the forked process](https://github.com/EnterpriseDB/barman/issues/686). This will be fixed in the next release.

**Comment by mikewallace1979** [comment] 2022-11-16 11:13
Was auto-closed by a merge but really this should stay open until we verify the underlying issue is resolved.

**Comment by pru-anixe** [comment] 2022-12-15 11:34
I can confirm that with version 3.3.0 I can execute backup properly from replica. Thanks!

**Comment by mikewallace1979** [comment] 2022-12-15 11:45
Great news - thanks for reporting back!

**Closed** 2022-12-15 11:45 UTC
Labels: triage
